name: 🗺️ Generate Sitemap Automatically

on:
  push:
    branches:
      - main  # غيّرها إذا كان فرعك الرئيسي اسمه master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate sitemap.xml
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml
          
          # إنشاء قائمة بجميع ملفات HTML داخل مجلد store
          for file in $(find store -type f -name "*.html" | sort); do
            url="https://yournaouma.github.io/${file}"   # 🔗 هذا الآن رابط موقعك الكامل
            lastmod=$(git log -1 --format=%cs "$file" || echo "$(date +%Y-%m-%d)")
            echo "  <url>" >> sitemap.xml
            echo "    <loc>${url}</loc>" >> sitemap.xml
            echo "    <lastmod>${lastmod}</lastmod>" >> sitemap.xml
            echo "    <changefreq>weekly</changefreq>" >> sitemap.xml
            echo "    <priority>0.8</priority>" >> sitemap.xml
            echo "  </url>" >> sitemap.xml
          done

          echo '</urlset>' >> sitemap.xml

      - name: Commit and push sitemap.xml
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"
          git add sitemap.xml
          git commit -m "🔄 Update sitemap automatically" || echo "No changes to commit"
          git push
